# Inspired by: https://github.com/JetBrains/intellij-platform-plugin-template/blob/main/.github/workflows/release.yml

name: Release
on:
  release:
    types: [prereleased, released]

jobs:
  # Prepare and publish the plugin to the Marketplace repository
  release:
    name: Build and release mod to github
    runs-on: ubuntu-latest
    steps:
      # Set environment variables
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2

      # Read release changelog
      - name: Read back changelog from release
        id: properties
        shell: bash
        run: |
          CHANGELOG="$(cat << 'EOM' | sed -e 's/^[[:space:]]*$//g' -e '/./,$!d'
          ${{ github.event.release.body }}
          EOM
          )"
          
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo "$CHANGELOG" >docs/LATEST_CHANGES.md
          cat docs/LATEST_CHANGES.md docs/CHANGELOG.md > /tmp/out && mv /tmp/out docs/CHANGELOG.md

          echo "::set-output name=changelog::$CHANGELOG"

      # Build the mod
      - name: Build the mod
        run: ./gradlew build

      # Upload mod as a release asset
      - name: Upload mod to github releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ./forge/build/libs/*-forge.jar ./fabric/build/libs/*-fabric.jar

      # Publish the mod to curseforge and modrinth
      - name: Upload Mod
        run: ./gradlew publishUnified --stacktrace
        env:
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          BRANCH_NAME: ${{ github.ref }}

      # Create pull request for updated changelog
      - name: Create Pull Request
        if: ${{ steps.properties.outputs.changelog != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          BRANCH="changelog-update-$VERSION"
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git checkout -b $BRANCH
          git commit -am "Changelog update - $VERSION"
          git push --set-upstream origin $BRANCH
          gh pr create \
            --title "Changelog update - \`$VERSION\`" \
            --body "Current pull request contains patched \`CHANGELOG.md\` file for the \`$VERSION\` version." \
            --base master \
            --head $BRANCH


